/** @type {import('tailwindcss').Config} */
// Palette generated by the UI/UX Pro Max skill for a dark developer dashboard
// (Dark Mode / OLED, midnight-slate base + green "run" accent). See
// ../DESIGN_SYSTEM.md. The whole app themes through these tokens — change a value
// here and every page follows.
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "Menlo", "monospace"],
      },
      colors: {
        // Surface ramp: app background → raised cards/inputs → hover/active.
        surface: {
          0: "#0f172a", // app background (midnight slate)
          1: "#1e293b", // cards, sidebar
          2: "#273349", // inputs, raised panels (muted)
          3: "#334155", // hover / secondary
          4: "#475569", // active / strongest fill
        },
        // Text hierarchy — semantic so contrast is consistent on the slate base.
        // Named `fg` to yield clean utilities: text-fg, text-fg-muted, etc.
        fg: {
          DEFAULT: "#f8fafc",
          secondary: "#cbd5e1",
          muted: "#94a3b8",
          faint: "#64748b",
        },
        border: {
          subtle: "rgba(148,163,184,0.10)",
          DEFAULT: "rgba(148,163,184,0.18)",
          strong: "#475569",
        },
        // Accent = interactive / brand / "run" (kept distinct from status green).
        accent: {
          DEFAULT: "#22c55e",
          hover: "#4ade80",
          muted: "rgba(34,197,94,0.14)",
          fg: "#052e16", // text/icon color on a filled accent surface
        },
        // Status palette — outcomes, never used as the brand accent.
        status: {
          success: "#10b981",
          "success-fg": "#34d399",
          warning: "#f59e0b",
          "warning-fg": "#fbbf24",
          danger: "#ef4444",
          "danger-fg": "#f87171",
          info: "#3b82f6",
          "info-fg": "#60a5fa",
        },
      },
      boxShadow: {
        // Elevation tuned for a dark UI: soft ambient + subtle top highlight.
        card: "0 1px 2px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.03) inset",
        raised: "0 4px 16px -2px rgba(0,0,0,0.5), 0 1px 0 rgba(255,255,255,0.04) inset",
        glow: "0 0 12px rgba(34,197,94,0.35)",
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
      },
      // Motion per the design system: ease-out entrances, 150–300ms, transform/
      // opacity only (no layout thrash). Used sparingly — one entrance per view
      // plus user-triggered micro-interactions. All neutralized by the global
      // prefers-reduced-motion rule in index.css.
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "pulse-slow": "pulse 3s ease-in-out infinite",
        "fade-in": "fade-in 200ms ease-out both",
        "fade-in-up": "fade-in-up 260ms ease-out both",
        "scale-in": "scale-in 180ms ease-out both",
        shimmer: "shimmer 1.6s infinite",
      },
    },
  },
  plugins: [],
};
